CREATE TABLE CMN_CD
(
    CODE       VARCHAR(50) PRIMARY KEY COMMENT '코드 (PK, ex: TAG_REFUND)',
    GROUP_CODE VARCHAR(50)  NOT NULL COMMENT '코드 그룹 (ex: TAG, CHN_CATEGORY)',
    NAME       VARCHAR(100) NOT NULL COMMENT '코드명 (ex: 환불, A/S문의)',
    SORT_ORDER INT     DEFAULT 0 COMMENT '정렬 순서',
    IS_USED    BOOLEAN DEFAULT TRUE COMMENT '사용 여부'
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4
  COLLATE = utf8mb4_unicode_ci COMMENT '공통 코드';


CREATE TABLE AGC
(
    ID     BIGINT PRIMARY KEY COMMENT '대리점 고유 ID (PK)',
    CODE   VARCHAR(20)  NOT NULL COMMENT '대리점 코드 (사업자등록번호 등, 고유값)',
    NAME   VARCHAR(100) NOT NULL COMMENT '대리점 이름',
    REG_DT TIMESTAMP DEFAULT CURRENT_TIMESTAMP() COMMENT '등록일시'
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4
  COLLATE = utf8mb4_unicode_ci COMMENT '대리점 핵심 정보';

ALTER TABLE AGC
    ADD COLUMN STATUS VARCHAR(20) NOT NULL DEFAULT 'ACTIVE' COMMENT '대리점 상태 (ACTIVE, DELETED)';

CREATE TABLE AGC_DTL
(
    AGC_ID    BIGINT PRIMARY KEY COMMENT '대리점 ID (PK, FK)',
    BIZ_NUM   VARCHAR(20) COMMENT '사업자등록번호',
    EMAIL     VARCHAR(100) COMMENT '연락용 이메일 주소',
    ZIP_CODE  VARCHAR(32) COMMENT '우편번호',
    BASE_ADDR VARCHAR(255) COMMENT '주소',
    DTL_ADDR  VARCHAR(255) COMMENT '상세주소',
    TEL       VARCHAR(20) COMMENT '연락처',
    CEO       VARCHAR(50) COMMENT '대표자명',
    FOREIGN KEY (AGC_ID) REFERENCES AGC (ID)
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4
  COLLATE = utf8mb4_unicode_ci COMMENT '대리점 상세 정보 (AGC 테이블과 1:1 관계)';

CREATE TABLE USR
(
    ID       BIGINT PRIMARY KEY COMMENT '사용자 고유 ID (PK)',
    LOGIN_ID VARCHAR(50) NOT NULL UNIQUE COMMENT '로그인 아이디 (고유값)',
    STATUS   VARCHAR(20) NOT NULL DEFAULT 'ACTIVE' COMMENT '사용자 상태 (ACTIVE, INACTIVE, DELETED)',
    NAME     VARCHAR(50) NOT NULL COMMENT '사용자 이름',
    ROLE     VARCHAR(20) NOT NULL COMMENT '권한 (ex: SUPER_ADMIN, OPERATOR, AGENT, AGENCY_ADMIN, AGENCY_REP)',
    AGC_ID   BIGINT COMMENT '소속된 대리점 ID (FK, Null일 경우 본사 소속)',
    REG_DT   TIMESTAMP            DEFAULT CURRENT_TIMESTAMP() COMMENT '가입일시',
    FOREIGN KEY (AGC_ID) REFERENCES AGC (ID)
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4
  COLLATE = utf8mb4_unicode_ci COMMENT '사용자 기본 정보';

CREATE TABLE USR_PW
(
    USR_ID BIGINT PRIMARY KEY COMMENT '사용자 ID (PK, FK)',
    PW     VARCHAR(255) NOT NULL COMMENT '암호화된 비밀번호',
    UPD_DT TIMESTAMP DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP() COMMENT '비밀번호 마지막 수정일시',
    FOREIGN KEY (USR_ID) REFERENCES USR (ID)
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4
  COLLATE = utf8mb4_unicode_ci COMMENT '사용자 비밀번호 (USR 테이블과 1:1 관계)';

CREATE TABLE USR_PW_LOG
(
    ID     BIGINT PRIMARY KEY COMMENT '로그 고유 ID (PK)',
    USR_ID BIGINT       NOT NULL COMMENT '사용자 ID (FK)',
    OLD_PW VARCHAR(255) NOT NULL COMMENT '변경 전 비밀번호 해시',
    REG_DT TIMESTAMP DEFAULT CURRENT_TIMESTAMP() COMMENT '등록일시',
    FOREIGN KEY (USR_ID) REFERENCES USR (ID)
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4
  COLLATE = utf8mb4_unicode_ci COMMENT '사용자 비밀번호 변경 이력을 기록하는 테이블';


CREATE TABLE CHN
(
    ID         BIGINT PRIMARY KEY COMMENT '채널 고유 ID (PK)',
    TYPE       VARCHAR(30) NOT NULL COMMENT 'CON or DM',
    TITLE      VARCHAR(255) COMMENT '채널 제목',
    CATEGORY   VARCHAR(50) COMMENT '문의 종류 (ex: A/S, 구매, 기술지원)',
    STATUS     VARCHAR(20) NOT NULL DEFAULT 'OPEN' COMMENT '채널 상태 (ex: OPEN, CLOSED)',
    CREATOR_ID BIGINT      NOT NULL COMMENT '채널을 생성한 사용자 ID (FK)',
    REG_DT     TIMESTAMP            DEFAULT CURRENT_TIMESTAMP() COMMENT '등록일시',
    FOREIGN KEY (CREATOR_ID) REFERENCES USR (ID)
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4
  COLLATE = utf8mb4_unicode_ci COMMENT '채널(문의/채팅방) 정보';

CREATE TABLE CHN_AGC_MAP
(
    CHN_ID BIGINT NOT NULL COMMENT '채널 ID (FK)',
    AGC_ID BIGINT NOT NULL COMMENT '대리점 ID (FK)',
    PRIMARY KEY (CHN_ID, AGC_ID),
    FOREIGN KEY (CHN_ID) REFERENCES CHN (ID),
    FOREIGN KEY (AGC_ID) REFERENCES AGC (ID)
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4
  COLLATE = utf8mb4_unicode_ci COMMENT '채널과 대리점의 다대다 관계 매핑 테이블';

CREATE TABLE CHN_LOG
(
    ID         BIGINT PRIMARY KEY COMMENT '로그 고유 ID (PK)',
    CHN_ID     BIGINT      NOT NULL COMMENT '채널 ID (FK)',
    USR_ID     BIGINT      NOT NULL COMMENT '상태를 변경한 사용자 ID (FK)',
    OLD_STATUS VARCHAR(20) COMMENT '변경 전 상태',
    NEW_STATUS VARCHAR(20) NOT NULL COMMENT '변경 후 상태',
    REG_DT     TIMESTAMP DEFAULT CURRENT_TIMESTAMP() COMMENT '등록일시',
    FOREIGN KEY (CHN_ID) REFERENCES CHN (ID),
    FOREIGN KEY (USR_ID) REFERENCES USR (ID)
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4
  COLLATE = utf8mb4_unicode_ci COMMENT '채널 상태 변경 로그';

CREATE TABLE CHN_USR_READ_STATUS
(
    CHN_ID           BIGINT    NOT NULL COMMENT '채널 ID (FK)',
    USR_ID           BIGINT    NOT NULL COMMENT '사용자 ID (FK)',
    LAST_READ_MSG_ID BIGINT    NULL COMMENT '마지막으로 읽은 메시지 ID (FK)',
    LAST_READ_DT     TIMESTAMP NULL COMMENT '마지막 읽음 처리 시간',
    PRIMARY KEY (CHN_ID, USR_ID),
    FOREIGN KEY (CHN_ID) REFERENCES CHN (ID) ON DELETE CASCADE,
    FOREIGN KEY (USR_ID) REFERENCES USR (ID) ON DELETE CASCADE,
    FOREIGN KEY (LAST_READ_MSG_ID) REFERENCES MSG (ID) ON DELETE SET NULL
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4
  COLLATE = utf8mb4_unicode_ci COMMENT '채널별 사용자 읽음 상태';

CREATE INDEX idx_chn_usr_read_status_usr ON CHN_USR_READ_STATUS (USR_ID);

CREATE TABLE MSG
(
    ID        BIGINT PRIMARY KEY COMMENT '메시지 고유 ID (PK)',
    CONTENT   TEXT   NOT NULL COMMENT '메시지 본문',
    CHN_ID    BIGINT NOT NULL COMMENT '메시지가 속한 채널 ID (FK)',
    SENDER_ID BIGINT NOT NULL COMMENT '메시지를 보낸 사용자 ID (FK)',
    REG_DT    TIMESTAMP DEFAULT CURRENT_TIMESTAMP() COMMENT '등록일시',
    FOREIGN KEY (CHN_ID) REFERENCES CHN (ID),
    FOREIGN KEY (SENDER_ID) REFERENCES USR (ID)
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4
  COLLATE = utf8mb4_unicode_ci COMMENT '메시지 내용';

CREATE TABLE MSG_FILE_MAP
(
    MSG_ID  BIGINT NOT NULL COMMENT '메시지 ID (FK to MSG.ID)',
    FILE_ID BIGINT NOT NULL COMMENT '파일 ID (FK to CMN_FILE.ID)',
    PRIMARY KEY (MSG_ID, FILE_ID), -- 복합 기본 키
    FOREIGN KEY (MSG_ID) REFERENCES MSG (ID) ON DELETE CASCADE, -- 메시지 삭제 시 매핑도 삭제
    FOREIGN KEY (FILE_ID) REFERENCES CMN_FILE (ID) -- 파일 삭제는 별도 관리 (CASCADE 안 함)
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4
  COLLATE = utf8mb4_unicode_ci COMMENT '메시지와 파일 매핑 정보';
CREATE INDEX idx_msg_file_map_file_id ON MSG_FILE_MAP (FILE_ID);


CREATE TABLE REFRESH_TOKEN
(
    USR_ID BIGINT PRIMARY KEY COMMENT '사용자 ID (PK, FK)',
    TOKEN  VARCHAR(255) NOT NULL COMMENT '리프레시 토큰',
    UPD_DT TIMESTAMP DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP() COMMENT '토큰 마지막 갱신일시',
    FOREIGN KEY (USR_ID) REFERENCES USR (ID)
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4
  COLLATE = utf8mb4_unicode_ci COMMENT '리프레시 토큰 정보';

CREATE TABLE CMN_FILE
(
    ID            BIGINT PRIMARY KEY COMMENT '파일 고유 ID (PK)',
    ORIGINAL_NAME VARCHAR(255) NOT NULL COMMENT '원본 파일명',
    STORED_PATH   VARCHAR(1024) NOT NULL COMMENT '서버 저장 경로 (파일명 포함)',
    FILE_TYPE     VARCHAR(100) COMMENT 'MIME 타입 (e.g., image/jpeg)',
    FILE_SIZE     BIGINT       NOT NULL COMMENT '파일 크기 (bytes)',
    UPLOADER_ID   BIGINT       NOT NULL COMMENT '업로드한 사용자 ID (FK to USR.ID)',
    UPLOAD_DT     TIMESTAMP DEFAULT CURRENT_TIMESTAMP() COMMENT '업로드 일시',
    FOREIGN KEY (UPLOADER_ID) REFERENCES USR (ID)
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4
  COLLATE = utf8mb4_unicode_ci COMMENT '공통 파일 정보';


ALTER TABLE USR
    ADD INDEX idx_usr_search (AGC_ID, STATUS, NAME);
-- 특정 대리점에 소속된 모든 사용자를 찾을 때
ALTER TABLE USR
    ADD INDEX idx_usr_agc_id (AGC_ID);
-- 특정 채널에 속한 모든 메시지를 시간순으로 불러올 때
ALTER TABLE MSG
    ADD INDEX idx_msg_chn_id (CHN_ID);

-- 특정 채널(CHN_ID)에 어떤 대리점들이 참여했는지 빠르게 찾기 위한 인덱스
-- (PK가 (CHN_ID, AGC_ID) 순서이므로 이미 이 인덱스는 자동 생성됩니다.)

-- 특정 대리점(AGC_ID)이 어떤 채널들에 참여했는지 빠르게 찾기 위한 인덱스 (필수 추가)
ALTER TABLE CHN_AGC_MAP
    ADD INDEX idx_chn_agc_map_agc_id (AGC_ID);
ALTER TABLE MSG
    ADD FULLTEXT INDEX idx_ft_msg_content (CONTENT);

-- 예시
-- '배송 문의' 라는 단어가 포함된 모든 메시지를 검색
-- SELECT * FROM MSG WHERE MATCH(CONTENT) AGAINST('배송 문의' IN BOOLEAN MODE);

ALTER TABLE USR
    ADD INDEX idx_usr_search (AGC_ID, STATUS, NAME);
-- 대시보드에서 '상태'와 '기간'으로 빠르게 필터링하기 위한 인덱스
ALTER TABLE CHN
    ADD INDEX idx_chn_status_reg_dt (STATUS, REG_DT);
-- 카테고리별 건수를 세는 기능은 위 복합 인덱스로는 처리하기 어려우므로, 별도의 단일 인덱스를 추가하는 것이 좋습니다.
ALTER TABLE CHN
    ADD INDEX idx_chn_category (CATEGORY);


-- 'ACTA' 대리점의 최근 3개월간 완료된 상담 건수를 카테고리별로 집계
# SELECT
#     CATEGORY,
#     COUNT(*) AS total_count
# FROM
#     CHN
# WHERE
#     AGC_ID = (SELECT ID FROM AGC WHERE NAME = 'ACTA')
#   AND STATUS = 'CLOSED'
#   AND REG_DT >= DATE_SUB(NOW(), INTERVAL 3 MONTH)
# GROUP BY
#     CATEGORY;


CREATE TABLE CMN_SEQ
(
    NAME          VARCHAR(50) NOT NULL PRIMARY KEY,
    CURRENT_VALUE BIGINT      NOT NULL
);


DELIMITER $$

CREATE FUNCTION GET_NEXT_SEQ_VAL(
    SEQ_NAME VARCHAR(50)
)
    RETURNS BIGINT
    MODIFIES SQL DATA
BEGIN
    INSERT INTO CMN_SEQ (NAME, CURRENT_VALUE)
    VALUES (SEQ_NAME, LAST_INSERT_ID(1))
    ON DUPLICATE KEY UPDATE CURRENT_VALUE = LAST_INSERT_ID(CURRENT_VALUE + 1);

    RETURN LAST_INSERT_ID();
END$$

DELIMITER ;


INSERT INTO CMN_CD (CODE, GROUP_CODE, NAME, SORT_ORDER, IS_USED)
VALUES ('SALES', 'CHN_CATEGORY', '영업문의', 10, TRUE),
       ('TECH', 'CHN_CATEGORY', '장애/기술지원', 20, TRUE),
       ('BILLING', 'CHN_CATEGORY', '청구/정산', 30, TRUE),
       ('ETC', 'CHN_CATEGORY', '기타', 90, TRUE);

INSERT INTO CMN_CD (CODE, GROUP_CODE, NAME, SORT_ORDER, IS_USED)
VALUES ('SUPER_ADMIN', 'USR_ROLE', '최고관리자', 10, TRUE),
       ('OPERATOR', 'USR_ROLE', '오퍼레이터', 20, TRUE),
       ('AGENCY_ADMIN', 'USR_ROLE', '대리점관리자', 30, TRUE);

INSERT INTO CMN_CD (CODE, GROUP_CODE, NAME, SORT_ORDER, IS_USED)
VALUES ('IN_PROGRESS', 'CHN_STATUS', '진행중', 20, TRUE),
       ('CLOSED', 'CHN_STATUS', '완료', 30, TRUE),
       ('WITHDRAWN', 'CHN_STATUS', '철회(나감)', 40, TRUE);